---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: CI

# Controls when the action will run. Workflow runs when manually triggered
# using the UI or API.
'on':
  push:
    branches:
      - '*'
  pull_request:
  schedule:
    - cron: '0 0 * * 6'

# A workflow run is made up of one or more jobs that can run sequentially or
# in parallel
jobs:
  test:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1 libopengl0

      - name: Install calibre
        run: ./scripts/update-calibre.sh

      - name: Build plugin ZIP files
        run: ./scripts/build.sh

      - name: Run tests
        run: ./scripts/test.sh
